language: php
php:
- 5.5
- 5.6
- 7.0
services:
- memcached
- redis
install:
- travis_retry composer self-update
- travis_retry composer require satooshi/php-coveralls "^1.0" --no-update --dev --prefer-dist
- travis_retry composer install
before_script:
- echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- phpenv rehash
script: phpunit -c phpunit.xml.dist
after_success:
- php vendor/bin/coveralls -v
cache:
  apt: true
  directories:
  - vendor
